### ISSUE TITLE
Add occ command for adding a client

### ISSUE THREAD

**Issue by cortho** [owncloud/oauth2#111] opened 2018-01-24 09:49 UTC
ATM it is only possible to add a new client manually by clicking in the Admin Settings.

An occ command performing this would make scriptable setups possible.

**Comment by SamuAlfageme** [comment] 2018-01-24 09:54
Duplicate of https://github.com/owncloud/oauth2/issues/94; there's some work already going on in https://github.com/owncloud/oauth2/pull/107 - @cortho the feedback from your experience there can be quite useful. Thanks!

Also some related discussion for EE usecases: https://github.com/owncloud/oauth2/issues/72

**Closed by SamuAlfageme** 2018-01-24 09:54 UTC
Labels: enhancement

**Comment by cortho** [comment] 2018-01-24 09:58
Sorry I missed this, thx.
