### ISSUE TITLE
Internal Server Error, if you try to add a client with an existing Name/URI

### ISSUE THREAD

**Issue by haukman** [owncloud/oauth2#162] opened 2018-09-13 08:14 UTC
Just discovered, that ownCloud throws an internal server error, if you try to register a client with the same name and URI as an existing one:

![kapture 2018-09-13 at 10 11 39](https://user-images.githubusercontent.com/25486818/45475794-a4c40d00-b73d-11e8-838b-c162cc83f5f7.gif)

oC 10.0.9
OAuth App: 0.2.2

**Comment by patrickjahns** [comment] 2018-09-17 22:28
probably duplicate of https://github.com/owncloud/oauth2/issues/135

**Comment by micbar** [comment] 2019-11-19 11:35
It fails in 0.4.2 RC2:

1) try to add a client that was already added (allowing subdomains)
2) try again to add a client that was already added (allowing subdomains)

![Screen Shot 2019-11-18 at 11 03 55](https://user-images.githubusercontent.com/10596560/69043612-ac430e00-09f3-11ea-9624-3fd3a77f10f4.png)


Current Result:

![Screen Shot 2019-11-18 at 11 04 58](https://user-images.githubusercontent.com/10596560/69043522-8289e700-09f3-11ea-8b6e-b9fd7d0cdc80.png)


```
{"reqId":"Bpfnkx0bqnwxllYpByhI","level":3,"time":"2019-11-18T10:04:49+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"index","method":"POST","url":"\/apps\/oauth2\/clients","message":"Caused by: {\"Exception\":\"PDOException\",\"Message\":\"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'iOS' for key 'name_idx'\",\"Code\":\"23000\",\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/PDOStatement.php(105): PDOStatement->execute(NULL)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(168): Doctrine\\\\DBAL\\\\Driver\\\\PDOStatement->execute(NULL)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(71): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(241): OC_DB_StatementWrapper->execute()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(119): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('INSERT INTO `*P...', Array)\\n#5 \\\/mnt\\\/data\\\/apps\\\/oauth2\\\/lib\\\/Controller\\\/SettingsController.php(122): OCP\\\\AppFramework\\\\Db\\\\Mapper->insert(Object(OCA\\\\OAuth2\\\\Db\\\\Client))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\OAuth2\\\\Controller\\\\SettingsController->addClient()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\OAuth2\\\\Controller\\\\SettingsController), 'addClient')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OAuth2\\\\Controller\\\\SettingsController), 'addClient')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\OAuth2\\\\\\\\Cont...', 'addClient', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(920): OC\\\\Route\\\\Router->match('\\\/apps\\\/oauth2\\\/cl...')\\n#12 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/PDOStatement.php\",\"Line\":105}"}
```


(cc @micbar )


It is reproducible in oauth 0.4.1 so it is not a regression for latest version.

**Comment by VicDeo** [comment] 2019-12-02 09:21
Fixed by https://github.com/owncloud/oauth2/pull/237

**Closed by VicDeo** 2019-12-02 09:21 UTC
Labels: bug
