### ISSUE TITLE
OAuth2 token revokation does not expire sessions

### ISSUE THREAD

**Issue by jesmrec** [owncloud/oauth2#103] opened 2017-12-01 12:21 UTC
### Steps to reproduce
1. Create a new OAuth2 session:

![screen shot 2017-12-01 at 13 16 14](https://user-images.githubusercontent.com/14894746/33482590-10f6008a-d69a-11e7-89b0-f98d530eb1cf.png)

2. Remove the authorized OAuth2 token in webUI `Security` section 

### Expected behaviour
Sessions for this client/user agent are removed/invalidated as well

### Current behaviour
Sessions keep alive, all request are reponsed with 200

![screen shot 2017-12-01 at 13 17 02](https://user-images.githubusercontent.com/14894746/33482597-1bff8d66-d69a-11e7-8f44-aae7604fcd41.png)

Set up:
- ownCloud 10.0.4 RC1 (daily) Build:2017-12-01T04:16:36+00:00 d4eab96823baec0061bc221e35b49dce968cbed9

- OAuth 0.2.1

**Comment by PVince81** [comment] 2017-12-04 12:29
@DeepDiver1975 @pmaier1

**Comment by Dagefoerde** [comment] 2017-12-04 13:18
Why do token-authenticated requests even create a session? I'd expect token-authenticated requests to be (rather) stateless, as the token is transmitted with every request. Therefore I think that such requests should not result in a session in the PHP sense at all, since that could be used to circumvent the token.

**Comment by DeepDiver1975** [comment] 2017-12-04 14:29
@Dagefoerde you are absolutely right - this is some technical dept about the session handling ....

**Comment by DeepDiver1975** [comment] 2017-12-04 14:46
@Dagefoerde you are absolutely right - this is some technical dept about the session handling ....

**Comment by DeepDiver1975** [comment] 2017-12-04 14:47
ok - there is an issue in UserSession::verifyAuthHeaders - not all scenarios are covered .....

**Comment by SamuAlfageme** [comment] 2017-12-04 14:58
Yup, I'll suggest moving this to core since "client-associated-session revocation" does work out of the box. For individual session revocation (not yet supported) refer to https://github.com/owncloud/oauth2/issues/97

Core is both generating a valid cookie (like @Dagefoerde pointed out in https://github.com/owncloud/oauth2/issues/103#issuecomment-348959627) and also accepting it (i.e. not ignoring) as authentication mechanism. A client sending both, an expired/revoked auth. token and this cookie therefore continues working normally. The same would apply for other stateless/token-based methods (e.g. app. passwords)...

**Comment by PVince81** [comment] 2017-12-18 09:59
So next step is https://github.com/owncloud/core/issues/29779 ?

**Comment by jesmrec** [comment] 2017-12-19 09:01
should be. At least, OAuth2 does not have to handle cookie sessions. The validity of the token should be enough to determine if the client is allowed to perform actions.

**Comment by michaelstingl** [comment] 2017-12-22 10:34
@PVince81 quick-fix: just drop the sessions?

**Comment by PVince81** [comment] 2017-12-22 11:13
@DeepDiver1975 can we do a quick fix and drop the sessions only for oauth, not in a broader scope ? (the broader scope needs more discussion)

**Comment by PVince81** [comment] 2017-12-22 11:21
The code must likely be added here: https://github.com/owncloud/oauth2/blob/master/lib/Controller/SettingsController.php#L177

I had a look at the DB structure and it seems we don't have a mapping between OAuth token and sessions.
However it is likely that core's `DefaultTokenProvider` also stores an entry in "oc_authtoken" that uses the OAuth token as password. So this entry could be invalidated explicitly in the above code.

**Comment by SamuAlfageme** [comment] 2018-02-05 13:55
I'd set the expectations for this as "remove and invalidate the orphaned sessions created when using OAuth" as Auth8N method, as:

> I'd expect token-authenticated requests to be (rather) stateless, as the token is transmitted with every request.

This is yet not possible considering the cookies are required for some core features to work IIRC.

> Sessions keep alive, all request are replied with 200: Success 

This is the part not reproducible as for today (10.0.6) - in contrast with the similar: https://github.com/owncloud/core/issues/28553. We should recap everything sessions-related to work towards the same goal.

**Closed** 2018-02-13 17:11 UTC
Labels: QA-known, bug

**Comment by SamuAlfageme** [comment] 2018-02-13 17:30
Relabeling because of https://github.com/owncloud/core/pull/30365#issuecomment-365335101 -> moved to mobile team backlog.
